---
version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.8.1 
    container_name: elasticsearch
    hostname: "elasticsearch"

    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: false

    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://elasticsearch:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5

    ports:
      - 9200:9200
      - 9300:9300
      
  logstash:
    image: logstash:8.8.1
    container_name: logstash
    hostname: "logstash"
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
        - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./wordlists/password.txt:/usr/share/logstash/data/password.txt
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: kibana:8.8.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
  api:
    container_name: api
    build: 
      dockerfile: 
          api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./check_index.sh:/app/check_index.sh
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: bash -c "/app/check_index.sh && /app/LeakGuard"
    


